name: Tokamak Geth Publish (Nightly Version)

on:
  push:
    branches:
      - 'main'

jobs:
  version:
    name: Get version (nightly)
    runs-on: ubuntu-latest
    # map the step outputs to job outputs
    outputs:
      nightly-docker-tag: ${{ steps.docker-image-name.outputs.nightly-docker-tag }}
    steps:
      - name: Check out source code
        uses: actions/checkout@v4
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0

      - name: Docker Image Name
        id: docker-image-name
        run: |
          echo "nightly-docker-tag=nightly-${GITHUB_SHA::8}" >> "$GITHUB_OUTPUT"

  start-runners:
    name: Start EC2 Runner
    runs-on: ubuntu-latest
    outputs:
      label: ${{ steps.start-ec2-runner.outputs.label }}
      ec2-instance-id: ${{ steps.start-ec2-runner.outputs.ec2-instance-id }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Start EC2 runner
        id: start-ec2-runner
        uses: machulav/ec2-github-runner@v2
        with:
          mode: start
          github-token: ${{ secrets.ACCESS_TOKEN }}
          ec2-image-id: ami-0ceeb1418a9676af7
          ec2-instance-type: t4g.2xlarge
          subnet-id: subnet-04958ddab1cb88c55
          security-group-id: sg-031082ccee7540e7a
          iam-role-name: ec2-runner
          pre-runner-script: shutdown -P +40

      - name: Runner status
        id: status
        run: |
          echo "Runner label:" ${{ steps.start-ec2-runner.outputs.label }}
          echo "EC2 instances id:" ${{ steps.start-ec2-runner.outputs.ec2-instance-id }}

  ec2-update-arm64:
    name: Update EC2 ${{ needs.start-runners.outputs.ec2-instance-id }}
    needs: [start-runners, version]
    runs-on: ARM64
    steps:
      - name: update shutdown behavior
        run: |
          aws ec2 modify-instance-attribute --instance-initiated-shutdown-behavior terminate --instance-id ${{ needs.start-runners.outputs.ec2-instance-id }}

  docker:
    name: Docker build and push
    needs: [start-runners, version, ec2-update-arm64]
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        runner: [ubuntu-latest, ARM64]
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_ACCESS_TOKEN_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN_SECRET }}

      - name: Docker Image Name
        id: docker-image-name
        run: |
          ARCHITECTURE=$(uname -m)
          if [ "$ARCHITECTURE" = "x86_64" ]; then
            ARCHITECTURE="amd64"
          fi
          if [ "$ARCHITECTURE" = "aarch64" ]; then
            ARCHITECTURE="arm64"
          fi
          echo "docker-image-name=tokamaknetwork/thanos-op-geth:${{ needs.version.outputs.nightly-docker-tag }}-$ARCHITECTURE" >> "$GITHUB_OUTPUT"

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          provenance: false
          tags: ${{ steps.docker-image-name.outputs.docker-image-name }}

  stop-runners:
    name: Stop self-hosted EC2 runners
    needs: [start-runners, docker]
    runs-on: ubuntu-latest
    if: ${{ always() }} # required to stop the runner even if the error happened in the previous jobs
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Stop EC2 runner
        uses: machulav/ec2-github-runner@v2
        with:
          mode: stop
          github-token: ${{ secrets.ACCESS_TOKEN }}
          label: ${{ needs.start-runners.outputs.label }}
          ec2-instance-id: ${{ needs.start-runners.outputs.ec2-instance-id }}

  merge:
    name: Build multi-arch images
    needs: [docker, version]
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_ACCESS_TOKEN_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN_SECRET }}

      - name: Create and push manifest
        uses: Noelware/docker-manifest-action@master
        with:
          inputs: tokamaknetwork/thanos-op-geth:nightly, tokamaknetwork/thanos-op-geth:${{ needs.version.outputs.nightly-docker-tag }}
          images: tokamaknetwork/thanos-op-geth:${{ needs.version.outputs.nightly-docker-tag}}-amd64,tokamaknetwork/thanos-op-geth:${{ needs.version.outputs.nightly-docker-tag }}-arm64
          push: true

  update-kustomize:
    name: Update image version in kustomize manifest file(nightly)
    needs:
      - version
      - docker
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: tokamak-network/tokamak-infra
          ref: main
          token: ${{ secrets.ACCESS_TOKEN }}
          path: tokamak-infra

      - name: Setup Kustomize
        uses: imranismail/setup-kustomize@v1
        with:
          github-token: ${{ secrets.ACCESS_TOKEN }}

      - name: Update thanos-op-geth Kubernetes resources
        run: |
          cd tokamak-infra/thanos/overlays/thanos-sepolia-test
          kustomize edit set image tokamaknetwork/thanos-op-geth:${{ needs.version.outputs.nightly-docker-tag}}

      - name: Show updated Kubernetes resources
        run: |
          cd tokamak-infra/thanos/overlays/thanos-sepolia-test
          cat kustomization.yaml

      - name: Commit and push changes
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          github_token: ${{ secrets.ACCESS_TOKEN }}
          message: '[AUTO] Update tokamak-thanos-geth image tags for sepolia'
          cwd: 'tokamak-infra/'
