name: Tokamak Geth Publish

on:
  push:
    tags:
      - 'release-*'

jobs:
  docker:
    name: Docker build and push
    runs-on: ubuntu-latest
    steps:
      - name: Get versions
        id: extractver
        run: echo "RELEASE=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_ACCESS_TOKEN_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN_SECRET }}

      - name: Build and push for AMD
        uses: docker/build-push-action@v6
        with:
          push: true
          provenance: false
          tags: tokamaknetwork/thanos-op-geth:${{ steps.extractver.outputs.RELEASE }}-amd64

      - name: Build and push for ARM
        uses: docker/build-push-action@v6
        with:
          push: true
          provenance: false
          platforms: linux/arm64
          file: Dockerfile_ARM
          tags: tokamaknetwork/thanos-op-geth:${{ steps.extractver.outputs.RELEASE }}-arm64

  merge:
    name: Build multi-arch images
    needs: [docker]
    runs-on: ubuntu-latest
    steps:
      - name: Get versions
        id: extractver
        run: echo "RELEASE=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_ACCESS_TOKEN_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN_SECRET }}

      - name: Create and push manifest
        uses: Noelware/docker-manifest-action@master
        with:
          inputs: tokamaknetwork/thanos-op-geth:${{ steps.extractver.outputs.RELEASE }}
          images: tokamaknetwork/thanos-op-geth:${{ steps.extractver.outputs.RELEASE }}-amd64,tokamaknetwork/thanos-op-geth:${{ steps.extractver.outputs.RELEASE }}-arm64
          push: true
