name: Tokamak Geth Publish (Nightly Version)

on:
  push:
    branches:
      - 'main'

jobs:
  version:
    name: Get version (nightly)
    runs-on: ubuntu-latest
    # map the step outputs to job outputs
    outputs:
      nightly-docker-tag: ${{ steps.docker-image-name.outputs.nightly-docker-tag }}
    steps:
      - name: Check out source code
        uses: actions/checkout@v4
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0

      - name: Docker Image Name
        id: docker-image-name
        run: |
          echo "nightly-docker-tag=nightly-${GITHUB_SHA::8}" >> "$GITHUB_OUTPUT"

  docker:
    name: Docker build and push
    needs: version
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_ACCESS_TOKEN_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN_SECRET }}

      - name: Build and push for AMD
        uses: docker/build-push-action@v6
        with:
          push: true
          provenance: false
          tags: tokamaknetwork/thanos-op-geth:${{ needs.version.outputs.nightly-docker-tag }}-amd64

      - name: Build and push for ARM
        uses: docker/build-push-action@v6
        with:
          push: true
          provenance: false
          platforms: linux/arm64
          file: Dockerfile_ARM
          tags: tokamaknetwork/thanos-op-geth:${{ needs.version.outputs.nightly-docker-tag }}-arm64

  merge:
    name: Build multi-arch images
    needs: [docker, version]
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_ACCESS_TOKEN_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN_SECRET }}

      - name: Create and push manifest
        uses: Noelware/docker-manifest-action@master
        with:
          inputs: tokamaknetwork/thanos-op-geth:nightly, tokamaknetwork/thanos-op-geth:${{ needs.version.outputs.nightly-docker-tag }}
          images: tokamaknetwork/thanos-op-geth:${{ needs.version.outputs.nightly-docker-tag}}-amd64,tokamaknetwork/thanos-op-geth:${{ needs.version.outputs.nightly-docker-tag }}-arm64
          push: true

  update-kustomize:
    name: Update image version in kustomize manifest file(nightly)
    needs:
      - version
      - docker
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: tokamak-network/tokamak-infra
          ref: main
          token: ${{ secrets.ACCESS_TOKEN }}
          path: tokamak-infra

      - name: Setup Kustomize
        uses: imranismail/setup-kustomize@v1
        with:
          github-token: ${{ secrets.ACCESS_TOKEN }}

      - name: Update thanos-op-geth Kubernetes resources
        run: |
          cd tokamak-infra/thanos/overlays/thanos-sepolia
          kustomize edit set image tokamaknetwork/thanos-op-geth:${{ needs.version.outputs.nightly-docker-tag}}

      - name: Show updated Kubernetes resources
        run: |
          cd tokamak-infra/thanos/overlays/thanos-sepolia
          cat kustomization.yaml

      - name: Commit and push changes
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          github_token: ${{ secrets.ACCESS_TOKEN }}
          message: '[AUTO] Update tokamak-thanos-geth image tags for sepolia'
          cwd: 'tokamak-infra/'
